### PR TITLE
fixed fountain-export-view to actually open the most recent file

### PR DESCRIPTION
**Pull request by ZungBang**
was sorting by wrong attribute (access-time), since the car of each
entry in file-list is the file name and the attributes follow

### CODE REVIEW

**Comment by ZungBang** [comment]
Originally this was `(file-attribute-modification-time (cdr ...))` but this seems to not be backwards compatible with Emacs before v26, so I changed it to `(nth 5 (cdr ...))` because 5 is the index of the modification time in the attributes list and is documented as such in [`file-attributes`](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Attributes.html). 

It does look kinda awkward. I'll change this if you want.

**Comment by rnkn** [comment]
Yeah let's just use 6 👍

**Comment by ZungBang** [comment]
Done.

**Comment by rnkn** [comment]
Thanks!

**Pull request merged**
